[package]
name = "airlift"
version = "0.1.0"
authors = ["Matthew Gleich <email@mattglei.ch>"]
edition = "2018"

[dependencies]
embedded-graphics = "0.6.0"
linux-embedded-hal = "0.3.0"
ssd1306 = "0.4.0"
ctrlc = { version = "3.0", features = ["termination"] }
